### ISSUE TITLE
Feature Request: disable publish logging by default

### ISSUE THREAD

**Issue by ronopitz** [schimaere/node-red-contrib-natsstreaming#2]
Hi,
at the moment, every published message creates a log entry.
In my environment I comment out the line 69 in the file nats-streaming-publish.js

    node.log('published message with guid: ' + guid);

Suggestion: Add a checkbox to the publish node configuration form to enable debugging.
Only when debugging is enabled the messages will be write to the log.
Thanks

**Comment by schimaere** [comment]
Hi,
I added a checkbox to the publish node to activate logging. 
Default is no logging.
